TamingSpeedMultiplier=15.0
HarvestAmountMultiplier=15.0
XPMultiplier=3.0
MatingIntervalMultiplier=0.1
BabyMatureSpeedMultiplier=50.0
EggHatchSpeedMultiplier=50.0
BabyCuddleIntervalMultiplier=0.1
BabyImprintAmountMultiplier=10.0
HexagonRewardMultiplier=2.0
bPvPDinoDecay=false
bPvPStructureDecay=false
CropGrowthSpeedMultiplier=200
MatingSpeedMultiplier=4


#DisableWorldBuffs=MATINGINTERVAL_DOWN_HARD,MATINGINTERVAL_DOWN_MEDIUM,MATINGINTERVAL_DOWN_EASY,BABYMATURE_BOON_EASY,BABYMATURE_BOON_MEDIUM,BABYMATURE_BOON_HARD
